#!/bin/sh
#
# @name Skywalker X8
# @type Fixedwing
#

. ${R}etc/init.d/rc.skywalker_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=skywalker_x8}


param set-default SIM_GZ_EN 1

param set-default SENS_EN_ARSPDSIM 1

param set-default FW_LND_ANG 8

# Enable fixed-wing auto-takeoff
param set-default FW_THR_IDLE 0.4 #0.15

# Motor failure detection (left as VTOL legacy – can be adjusted as needed)
param set-default FD_ACT_EN 0
param set-default FD_ACT_MOT_TOUT 500

param set-default CA_AIRFRAME 1
param set-default COM_PREARM_MODE 2
param set-default FW_W_EN 1
param set-default RWTO_TKOFF 1

# Fixed-wing: Only one rotor (the pusher prop)
param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_AX 1
param set-default CA_ROTOR0_AZ 0
param set-default CA_ROTOR0_PX 0.2

# Only one motor (the tail rotor)
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MAX1 1000

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203

param set-default COM_RC_IN_MODE 1

param set-default CA_SV_CS_COUNT 3
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS2_TRQ_P 1

param set-default NPFG_PERIOD 12

param set-default FW_PR_FF 0.2
param set-default FW_PR_P 0.9
# param set-default FW_PR_I 0.5
# param set-default TRIM_PITCH -0.15
param set-default FW_PSP_OFF 2 # 0
param set-default FW_P_LIM_MIN -15 # -15

param set-default FW_RR_FF 0.1 # 0.5
param set-default FW_RR_P 0.3 # 0.4
# param set-default FW_RR_I 0.7

#param set-default FW_R_RMAX 56.15

param set-default FW_THR_TRIM 0.25
param set-default FW_THR_MAX 0.6
param set-default FW_THR_MIN 0.05

param set-default FW_T_CLMB_MAX 8 # 5
param set-default FW_T_SINK_MAX 2.7 # 3.5
param set-default FW_T_SINK_MIN 2.2 # 3

param set-default MIS_TAKEOFF_ALT 30


#param set-default MPC_XY_P 0.8
#param set-default MPC_XY_VEL_P_ACC 3
#param set-default MPC_XY_VEL_I_ACC 4
#param set-default MPC_XY_VEL_D_ACC 0.1

param set-default NAV_ACC_RAD 5 # 15
param set-default NAV_DLL_ACT 2

param set-default FD_ESCS_EN 0
